name: Auto Split Playlist

on:
  push:
    branches:
      - main

  workflow_dispatch:

  schedule:
    - cron: '0 */6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Download latest master playlist
        run: |
          curl -L --fail --retry 3 \
            "https://raw.githubusercontent.com/Prtstream820894/Prmovies/refs/heads/main/playlist.m3u?t=$(date +%s)" \
            -o playlist.m3u

      - name: Run splitting script
        run: python split_playlist.py

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add playlists/ playlists.json playlist.m3u

          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Auto-update split playlists and json"
            git push
          fi
